---
title: Niet botsen!
hero_image: images/banner.png
description: Bouw een eindeloos 'runner game' waarin je personage moet voorkomen dat hij tegen obstakels aanbotst
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - title: Inleiding
  - title: Het opzetten van het thema
  - title: Maak obstakels
    completion: engaged
  - title: Botsingsdetectie
  - title: Versnellen!
    completion: internal
  - title: Reflectie
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: Verbeter je project
    completion: external
  - title: Deel
  - title: Wat kun je verder nog doen?
